#+TITLE: Trip To Malana
#+AUTHOR: Thirumal Ravula
#+DATE: [2016-11-01 Tue]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil


I for some time in recent times felt like a drooping flag of the days of yore.
The ideas are all right there, there is a strong confidence in me that I might
be pretty sure of an imperative for alternate ways of socio-economic
organizations.  I wanted this break, to ponder over again and make those direct
conversations with me: if I truly believed in things I am supposed to be
espousing for?  What are those alternatives?  What really went wrong in the
last two centuries that has started so brightly with the [[https://en.wikipedia.org/wiki/Storming_of_the_Bastille][Storming of the
Bastille]].

I have got 5 days and four nights to trek in the Parvathi Valley at the
foothills of Himalayas in Himachal Pradesh.  Lonely Planet's 'Trekking in
Himalayas' lists a trek from Nagar to Kasol passing over chadrakhani and rasol
passes spanning the time I had.  Only difference is I was planning to start at
the other end - Kasol - and end up in Nagar.

The purpose of my Delhi visit was to present the stuff we have been doing over
the past year.  The review went well and I had an interesting chat with a
professor who he says is currently working with a student of his
student. Pretty trippy, but that is true.  Our talk during the walk to the
guest house for lunch from CS department building gave me satisfaction that
there are others who are working on the solutions to build organizations
without hierarchy while in sound harmony with the nature; sustainable societies
materially and spiritually.  But the previous day did not start that well.  The
strap to my back pack broke while getting the pack out of the trunk adding
another dimension to the unknown that lay ahead in the coming days both in
space and in time.  Should I get this bag repaired in Delhi? Get a new bag, or
get a new day pack, stay at Kasol and do day treks along and around Parvathi
nadi? while the perennial distraction of the work lay a seize to my mind to the
point of numbing it, since some of our software that was released recently was
in production.

The professor and I exchanged phone numbers and e-mail addresses to tap on each
other for support, critique and collaboration.  Dr. Srivathsan has a working
solution that can generate surplus solar energy and use it at the origin to
serve the local needs like sewage treatment, water purification, compost
generation, etc.  He has given me an open invitation to stay at his college and
work on making this solar power solution a possibility.  Murray Bokchin, an
anarchist and an ecologist, felt that climate change will be the grave digger
of Capitalism.  But in times of real challenge to mankind, the humanity has the
power to resuscitate itself while in the melee there would emerge technologies
that can be shaped to build communities that operate on trust and collaboration
where there is no such thing as waste or polluted.  Renewable energy and
miniaturization of technologies are the key ingredients of this potion.  With
these thoughts I headed to the hotel but the broken bag brought me back to
reality.  The sudden feeling of optimism emanating by the turn of events that
day urged me to get the bag repaired and do the full trek.  The tailors sitting
on the terraces at the Sarojini Devi Market did an efficient job of fixing my
bag while I feasted on momos nearby and by 10:00 PM, I am on the bus to Kulu,
Himachal Pradesh.  I should get off at Bunthar a few kilometers before Kulu, I
will be getting there by 10:00 AM te next morning which is [2016-10-22 Sat]


 
