#+TITLE: Trip To Malana - Part II
#+AUTHOR: Thirumal Ravula
#+DATE: [2017-01-04 Wed]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

What is it that we live for?  I guess to make an effort to leave an idea that
can add beauty to the world.  With these thoughts I woke up at the gates of
interstate border check post of Himachal Pradesh.  A policeman checked inside
and found a huge bag with loads of alcohol.  The guy sitting next to me
acknowledged his ownership of the bag.  He is taking them to a relative's
marriage and he is from armed service.  The policeman got down the bus while
we would be doing steep climbs along the river Baes.  To break the monotony I
would do foot boarding and lean over the locked door to breathe in the whole
mountains while soaking in the light from the increasing glimpses of sun.


Getting off at Kasol, the state I am in seemed a drag on myself and the weekend
crowd set my spirits to droop.  The tiredness from sitting in the bus for this
while tended to seed in me to take short cuts.  One of them was prodding me to
stay put there for the night, chill out, take a drag or two.  The easy way is
to blame it on the lack of energy but the real issue was that I got to the base
two hours later than what I had planned from my intuition stemming from my read
of the trek both from the book and the personal blogs of other trekkers and
revellers.  One blog mentioned that people do not leave this place as planned
but would end up staying for weeks and in few cases for months.  That is the
charm this place has.  

The center where the bus dropped me, seemed to have of people and my immediate
instinct took me I wanted to get off and stay at a quieter place.  I still have
to figure out the trek from Kasol where I am now to Malana.

